export const nationCodes = {
  0: "Austria",
  1: "France",
  2: "England",
  3: "Spain",
  4: "Russia",
  5: "Ukraine",
  6: "Poland",
  7: "Sweden",
  8: "Prussia",
  9: "Venice",
  10: "Turkey",
  11: "Algeria",
  13: "Netherlands",
  14: "Denmark",
  15: "Portugal",
  16: "Piedmont",
  17: "Saxony",
  18: "Bavaria",
  19: "Hungary",
  20: "Switzerland",
  21: "Scotland",
  24: "Random"
};